### ISSUE TITLE
Setup procedure not clear

### ISSUE THREAD

**Issue by TheBluePineapple** [cstoquer/pixelbox#7]

**Comment by pudarida** [comment]
Hi, what is not clear with the setup instructions? I find it pretty straightforward.

**Comment by TheBluePineapple** [comment]
Well, it seems to assume familiarity with node.js (which I wasn't familiar
with at all at the time I opened the issue), which can make it pretty
confusing for the unfamiliar. Something that could be done would be to
directly state that it requires node.js, like "Use of this tool requires
node.js, if you don't have it installed then please install".

**Comment by cstoquer** [comment]
I made some huge modifications to address the issue that you and some other users gave me at the time. From version 2.0.0, Pixelbox is now split in two components: this library, and a GUI editor available on [itch.io](https://pixwlk.itch.io/pixelbox).

If you are still interested by this project, please give it another try.

**Comment by ogrotten** [comment]
I think this is still a valid question. I've been around node a while, but I'm no node expert and it seems incomplete.

The readme here says "Building is done using browserify" but there's no `build` script in the package.json from this repo. As a matter of fact, there's only one script there, and it's for building the docs, which comes back with an error `FATAL: Unable to load template: Cannot find module './doc/templates/ink-docstrap/publish'` because the `./doc` dir didn't setup with the node install.

Then there's the question: which is the DL to use for a new project? The repo, or the itch download?

I'd love to give it a whirl, but there's a need for more starter docs.
